### PR TITLE
Fix OSX Flashing

### LINKED ISSUE #65: Mac OSX firmware flashing fail
Flashing a firmware on Mac OS seems to only work on 0.2.0 and previous.
All versions released after (0.2.11, 0.2.12, 0.2.12-RC2) are not able to flash the firmware:
The flight controller goes into DFU mode but then nothing happens.
0.2.0 seems to work fine even flashing the latest firmware.

### PR DESCRIPTION
**Pull request by nerdCopter**
* reportedly fixes flashing on MacOS version that previously failed
* update to nw-Builder dependency and gui fixes (workarounds) associated with such
* fixes #65. also reference #16, #51

### CODE REVIEW

File: src/js/chromeAppEventPage.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        }
+    });
+}
+
+chrome.app.runtime.onLaunched.addListener(startApplication);
+
+function getChromeVersion () {
+    const raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
+
+    return raw ? parseInt(raw[2], 10) : false;
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:26]: Codacy Issue found: [Ternary operator used.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/js/chromeAppEventPage.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000&bid=18271852)

File: src/js/chromeAppEventPage.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+function startApplication() {
+    chrome.app.window.create('main.html', {
+        id: 'main-window',
+        frame: 'chrome',
+        innerBounds: {
+            minWidth: 1024,
+            minHeight: 550,
+        },
+    }, function (createdWindow) {
+        if (getChromeVersion() >= 54) {
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:15]: Codacy Issue found: ['getChromeVersion' was used before it was defined.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js [hunk 3]
```diff
@@ -0,0 +1,27 @@
+/*
+    If an id is also specified and a window with a matching id has been shown before, the remembered bounds of the window will be used instead.
+*/
+'use strict';
+
+function startApplication() {
+    chrome.app.window.create('main.html', {
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:7]: Codacy Issue found: ['chrome' is not defined.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+            minHeight: 550,
+        },
+    }, function (createdWindow) {
+        if (getChromeVersion() >= 54) {
+            createdWindow.icon = 'images/bf_icon_128.png';
+        }
+    });
+}
+
+chrome.app.runtime.onLaunched.addListener(startApplication);
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:21]: Codacy Issue found: ['chrome' is not defined.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 2 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:15]: Codacy Issue found: [The numeric literal '54' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 1 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:26]: Codacy Issue found: [The numeric literal '10' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+    If an id is also specified and a window with a matching id has been shown before, the remembered bounds of the window will be used instead.
+*/
+'use strict';
+
+function startApplication() {
+    chrome.app.window.create('main.html', {
+        id: 'main-window',
+        frame: 'chrome',
+        innerBounds: {
+            minWidth: 1024,
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:11]: Codacy Issue found: [The numeric literal '1024' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+            minHeight: 550,
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:12]: Codacy Issue found: [The numeric literal '550' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

**Comment by nerdCopter** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 8
           

Complexity increasing per file
==============================
- src/js/chromeAppEventPage.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000&bid=18271852)

File: src/js/chromeAppEventPage.js [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+        }
+    });
+}
+
+chrome.app.runtime.onLaunched.addListener(startApplication);
+
+function getChromeVersion () {
+    const raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
+
+    return raw ? parseInt(raw[2], 10) : false;
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:26]: Codacy Issue found: [The numeric literal '10' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+            minHeight: 550,
+        },
+    }, function (createdWindow) {
+        if (getChromeVersion() >= 54) {
+            createdWindow.icon = 'images/emu_icon_128.png';
+        }
+    });
+}
+
+chrome.app.runtime.onLaunched.addListener(startApplication);
```
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:21]: Codacy Issue found: ['chrome' is not defined.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 6 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:12]: Codacy Issue found: [The numeric literal '550' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 5 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:11]: Codacy Issue found: [The numeric literal '1024' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 3 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:7]: Codacy Issue found: ['chrome' is not defined.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 2 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:15]: Codacy Issue found: ['getChromeVersion' was used before it was defined.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 7 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:26]: Codacy Issue found: [Ternary operator used.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: src/js/chromeAppEventPage.js (hunk 2 above)
Comment (nerdCopter) [inline src/js/chromeAppEventPage.js:15]: Codacy Issue found: [The numeric literal '54' will have at different value at runtime.](https://app.codacy.com/gh/emuflight/EmuConfigurator/pullRequest?prid=5573000)

File: gulpfile.js [hunk 9]
```diff
@@ -40,7 +40,7 @@ var gitChangeSetId;
 
 var nwBuilderOptions = {
     // FIXME: hardcoded version number
-    version: '0.42.2',
+    version: '0.46.0',
```
Comment (nerdCopter) [inline gulpfile.js:43]: 0.45.6 works, but 0.46.0 broke only Win7.
